services:
  nginx:
    image: nginx:alpine
    container_name: embarcatech-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - embarcatech-net

  api:
    build: ./api
    container_name: embarcatech-api
    expose:
      - "8000"
    environment:
      - PORT=8000
    networks:
      - embarcatech-net
    restart: unless-stopped

networks:
  embarcatech-net:
    driver: bridge
